<?php

namespace App\Test\Repository;

use App\Entity\CurrencyRate;
use App\Test\Service\AbstractCurrencyRateRepositoryTest;

class CurrencyRateRepositoryTest extends AbstractCurrencyRateRepositoryTest
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setRepositoryClassName(CurrencyRate::class);
    }
}